spring:
  datasource:
    url: jdbc:mysql://aliyun.com:3306/mall_pms?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: csmall
    password: P@ssw0rd

logging:
  level:
    cn.tedu.csmall.product: info